GET http://localhost:8080/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW4iLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTA0MzM0OTIsImV4cCI6MTY1MDUxOTg5Mn0.JQwF2f-W_rlQEaHcrHC8Yn51AiS9tfSLvFlfZSHpNGY

################################
POST http://localhost:8080/api/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW4iLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTA0MzM0OTIsImV4cCI6MTY1MDUxOTg5Mn0.JQwF2f-W_rlQEaHcrHC8Yn51AiS9tfSLvFlfZSHpNGY

{
    "nameRole":"Customert",
    "description":"Quyền dành cho khách hàngt"
}


################################
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username":"xuanquy",
    "password":"admin",
    "fullname":"Vũ Xuân Quý",
    "nameRole":"Customer",
    "email":"xuanquy@gmail.com",
    "phone":"08683323255",
    "address":"Tây Sơn Kiến Xương Thái Bình"
}


###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
   
}
########
POST http://localhost:8080/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQwMWRlM2M2YjE0ODYwMzU1ZjhmNjYiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NDgzNzUzNTQsImV4cCI6MTY0ODQ2MTc1NH0.g0BziTLB31MkChiQ8FEfh2LOaVzYwLx1CEA-ZpuUAbk

{
    "name":"Thiết Bị",
    "image":"https://cf.shopee.vn/file/7abfbfee3c4844652b4a8245e473d857_tn",
    "description":"Các Thiết Bị Điện Gia Dụng",
    "status":"1"
}

########
POST http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQwMWRlM2M2YjE0ODYwMzU1ZjhmNjYiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NDgzNzUzNTQsImV4cCI6MTY0ODQ2MTc1NH0.g0BziTLB31MkChiQ8FEfh2LOaVzYwLx1CEA-ZpuUAbk

{
    "name":"Đèn Học",
    "idCategory": "62401d6039d6273e67e013ac",
    "description":"Các Thiết Bị Điện Gia Dụng",
    "image":"https://cf.shopee.vn/file/87f4beea3d91ef3a50b699aa6dbd2a7c",
    "hide":"true",
    "quantity": "5",
    "price": "200000đ",
    "status":"1"
}