GET http://localhost:8080/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQwMWRlM2M2YjE0ODYwMzU1ZjhmNjYiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NDgzOTc1NDMsImV4cCI6MTY0ODQ4Mzk0M30.a2N72Hur_ppEupkGSr1yCFfupvnMxXnfMUEbDXh4AGQ

################################
POST http://localhost:8080/api/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjNiZTYxYTE0ODYyNjI0NjJmZmMwZWYiLCJpYXQiOjE2NDgwOTI4NTAsImV4cCI6MTY0ODE3OTI1MH0.7f41LJQLeSBHUt2BJ0i8EqD3pcEPa4IXFLNMYZjzSUA

{
    "nameRole":"Customer",
    "description":"Quyền dành cho khách hàng"
}


################################
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username":"hainhat",
    "password":"admin",
    "fullname":"Đặng Thị Hải Nhật",
    "nameRole":"Admin"
}


###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
   
}

########
POST http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjNiZTYxYTE0ODYyNjI0NjJmZmMwZWYiLCJyb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE2NDgyODMyODQsImV4cCI6MTY0ODM2OTY4NH0.m6WHVXRzpsSQh9ZYsyotfhADuWOg7nz6j4blp3FMano

{
    "name":"xuanquy",
    "image":"admin",
    "description":"Xuân Quý",
    "status":"0"
}