DELETE http://localhost:8080/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW5pc3RyYXRvcnMiLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTEyODUyNTcsImV4cCI6MTY1MTM3MTY1N30.LzVxTGY0Ed4aYghp6bKE2IKYMB4COzH1YFlKURAbsqk
#######################################
GET http://localhost:8080/api/manufacturer/allmanufacturer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW5pc3RyYXRvcnMiLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTIwMTQxNTUsImV4cCI6MTY1MjEwMDU1NX0.NMxcM0QSH4zqrlQ1dh6K7KfaMDQRdXXJYCh1v7dCmng
#########################
DELETE http://localhost:8080/api/manufacturer/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW5pc3RyYXRvcnMiLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTIwMTQxNTUsImV4cCI6MTY1MjEwMDU1NX0.NMxcM0QSH4zqrlQ1dh6K7KfaMDQRdXXJYCh1v7dCmng
################################
POST http://localhost:8080/api/manufacturer/addmanufacturer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW5pc3RyYXRvcnMiLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTIwMTQxNTUsImV4cCI6MTY1MjEwMDU1NX0.NMxcM0QSH4zqrlQ1dh6K7KfaMDQRdXXJYCh1v7dCmng

{
    "nameManufacturer":"7",
    "phone":"1234",
    "address":"hp",
    "mail":"a@gmail.com"
}

###########################
PUT http://localhost:8080/api/manufacturer/updatemanufacturer/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGUiOnsiaWQiOjEsIm5hbWVSb2xlIjoiQWRtaW5pc3RyYXRvcnMiLCJkZXNjcmlwdGlvbiI6IlF1eeG7gW4gY2hvIHF14bqjbiB0cuG7iyB2acOqbiJ9LCJpYXQiOjE2NTIwMTQxNTUsImV4cCI6MTY1MjEwMDU1NX0.NMxcM0QSH4zqrlQ1dh6K7KfaMDQRdXXJYCh1v7dCmng

{
    "nameManufacturer":"ô dù",
    "phone":"1234",
    "address":"TH",
    "mail":"a@gmail.com"
}